# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
Variables:
  intellix-connector:
    host: ''
    username: ''
    # [password]
    password: ''
    msName: ''
    
    # The Logon URL will be automatically determined.
    # If this variable is set (not-empty), this URL
    # will be taken as the Logon URL. It typically looks like
    # https://.../Acount/Logon
    # Only set this value, if the automatic determination does not work.
    logonurl: ''
